export const ActionTypes = {
    SET_ORGANIZATION: "SET_ORGANIZATION",
    FETCH_ORGANIZATION: "FETCH_ORGANIZATION",
    FETCH_FLEET_AGENCIES: "FETCH_FLEET_AGENCIES",
    ADD_FLEET_AGENCIES: "ADD_FLEET_AGENCIES",
    FETCH_USERS: "FETCH_USERS",
    FETCH_GUARD_AGENCIES: "FETCH_GUARD_AGENCIES",
    ADD_GUARD_AGENCIES: "ADD_GUARD_AGENCIES",
    EDIT_GUARD_AGENCIES: "EDIT_GUARD_AGENCIES",
    FETCH_GUARDS: "FETCH_GUARDS",
    HIDE_LOADER: "HIDE_LOADER",
    SHOW_LOADER: "SHOW_LOADER",
    ADD_GUARD: "ADD_GUARD",
    EDIT_GUARD: "EDIT_GUARD",
    DELETE_GUARD_AGENCY: "DELETE_GUARD_AGENCY",
    ACTIVE_GUARD_AGENCY: "ACTIVE_GUARD_AGENCY",
    DELETE_GUARD: "DELETE_GUARD",
    ACTIVE_GUARD: "ACTIVE_GUARD"
}