export const ActionTypes = {
    SET_ORGANIZATION: "SET_ORGANIZATION",
    FETCH_ORGANIZATION: "FETCH_ORGANIZATION",
    FETCH_FLEET_AGENCIES: "FETCH_FLEET_AGENCIES",
    ADD_FLEET_AGENCIES: "ADD_FLEET_AGENCIES",
    FETCH_USERS: "FETCH_USERS"
}